parsers:
  - url: https://example.com/profile.yaml
    yaml:
      append-rules:
      # prepend-rules:
        # new bingå¯¹åº”çš„åŸŸå
        - DOMAIN-SUFFIX,sydney.bing.com,newbing
        - DOMAIN-SUFFIX,www.bing.com,newbing
      append-proxy-groups:
        - name: newbing
          type: select
          proxies:
            - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
            - DIRECT